name: Deploy

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

env:
  APP_LOCATION: src/Web/ClientApp # location of your client code
  OUTPUT_LOCATION: dist # location of client code build output

jobs:
  build_and_deploy_angular:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Remove dev config file
        run: rm src/Web/ClientApp/environments/environment.ts
      - name: Add prod config file
        run: echo ${{ secrets.ANGULAR_ENV }} | base64 -d > src/Web/ClientApp/environments/environment.ts
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: ${{ env.OUTPUT_LOCATION }}
